package in.shvms.famt_be.service;

import in.shvms.famt_be.entity.AuditLog;
import in.shvms.famt_be.entity.Event;
import in.shvms.famt_be.entity.Person;
import in.shvms.famt_be.repositories.mongo.AuditLogRepository;
import in.shvms.famt_be.repositories.neo4j.EventRepository;
import in.shvms.famt_be.repositories.neo4j.LocationRepository;
import in.shvms.famt_be.repositories.neo4j.PersonRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.HashSet; // Needed for event.getParticipants() if it's null initially

@Service
@RequiredArgsConstructor
public class EventService {

    private final EventRepository eventRepository;
    private final PersonRepository personRepository;
    private final LocationRepository locationRepository; // Although not used in provided snippet, it's in the prompt
    private final AuditLogRepository auditLogRepository;

    // Helper method for audit logging
    private void logAudit(String tenantId, String userId, String action, String entityType, String entityId, Map<String, Object> details) {
        AuditLog auditLog = new AuditLog(
                null, // Id will be generated by MongoDB
                tenantId,
                LocalDateTime.now(),
                userId,
                action,
                entityType,
                entityId,
                details,
                null // IP address can be retrieved from request context if needed
        );
        auditLogRepository.save(auditLog);
    }

    public Event createEvent(String tenantId, String userId, Event event) {
        event.setTenantId(tenantId);
        // Initialize participants if null to prevent NullPointerException
        if (event.getParticipants() == null) {
            event.setParticipants(new HashSet<>());
        }
        Event savedEvent = eventRepository.save(event);
        logAudit(tenantId, userId, "CREATE", "Event", savedEvent.getId().toString(), Map.of("newEvent", savedEvent));
        return savedEvent;
    }

    public Optional<Event> getEventById(String tenantId, UUID id) {
        return eventRepository.findByTenantIdAndId(tenantId, id);
    }

    public List<Event> getAllEvents(String tenantId) {
        return eventRepository.findAllByTenantId(tenantId);
    }

    public Event updateEvent(String tenantId, String userId, UUID id, Event updatedEvent) {
        return eventRepository.findByTenantIdAndId(tenantId, id).map(event -> {
            Map<String, Object> oldEventDetails = Map.of(
                    "oldEventType", event.getEventType(),
                    "oldEventDate", event.getEventDate(),
                    "oldDescription", event.getDescription(),
                    "oldLocationId", event.getLocation() != null ? event.getLocation().getId() : null
            );
            
            event.setEventType(updatedEvent.getEventType());
            event.setEventDate(updatedEvent.getEventDate());
            event.setDescription(updatedEvent.getDescription());
            
            // Handle location update
            if (updatedEvent.getLocation() != null && updatedEvent.getLocation().getId() != null) {
                // Assuming LocationRepo can find a Location by its ID (String)
                locationRepository.findById(updatedEvent.getLocation().getId())
                        .ifPresent(event::setLocation);
            } else {
                event.setLocation(null); // Or throw error if location is mandatory
            }

            Event savedEvent = eventRepository.save(event);
            logAudit(tenantId, userId, "UPDATE", "Event", savedEvent.getId().toString(), Map.of(
                    "oldValues", oldEventDetails,
                    "newValues", Map.of(
                            "eventType", savedEvent.getEventType(),
                            "eventDate", savedEvent.getEventDate(),
                            "description", savedEvent.getDescription(),
                            "locationId", savedEvent.getLocation() != null ? savedEvent.getLocation().getId() : null
                    )
            ));
            return savedEvent;
        }).orElseThrow(() -> new RuntimeException("Event not found for tenant " + tenantId + " and ID " + id));
    }

    public void deleteEvent(String tenantId, String userId, UUID id) {
        Event eventToDelete = eventRepository.findByTenantIdAndId(tenantId, id)
                .orElseThrow(() -> new RuntimeException("Event not found for tenant " + tenantId + " and ID " + id));
        eventRepository.delete(eventToDelete);
        logAudit(tenantId, userId, "DELETE", "Event", id.toString(), Map.of("deletedEvent", eventToDelete));
    }

    public List<Event> getEventsByType(String tenantId, String eventType) {
        return eventRepository.findByTenantIdAndEventType(tenantId, eventType);
    }

    public Event addParticipantToEvent(String tenantId, String userId, UUID eventId, UUID personId) {
        Event event = eventRepository.findByTenantIdAndId(tenantId, eventId)
                .orElseThrow(() -> new RuntimeException("Event not found for tenant " + tenantId + " and ID " + eventId));
        Person person = personRepository.findByTenantIdAndId(tenantId, personId)
                .orElseThrow(() -> new RuntimeException("Person not found for tenant " + tenantId + " and ID " + personId));

        if (event.getParticipants() == null) {
            event.setParticipants(new HashSet<>());
        }
        event.getParticipants().add(person);
        Event savedEvent = eventRepository.save(event);
        logAudit(tenantId, userId, "ADD_PARTICIPANT", "Event", eventId.toString(), Map.of("personIdAdded", personId));
        return savedEvent;
    }

    public Event removeParticipantFromEvent(String tenantId, String userId, UUID eventId, UUID personId) {
        Event event = eventRepository.findByTenantIdAndId(tenantId, eventId)
                .orElseThrow(() -> new RuntimeException("Event not found for tenant " + tenantId + " and ID " + eventId));
        Person person = personRepository.findByTenantIdAndId(tenantId, personId)
                .orElseThrow(() -> new RuntimeException("Person not found for tenant " + tenantId + " and ID " + personId));

        if (event.getParticipants() != null) {
            event.getParticipants().remove(person);
        }
        Event savedEvent = eventRepository.save(event);
        logAudit(tenantId, userId, "REMOVE_PARTICIPANT", "Event", eventId.toString(), Map.of("personIdRemoved", personId));
        return savedEvent;
    }
}