package in.shvms.famt_be.service;

import in.shvms.famt_be.entity.AuditLog;
import in.shvms.famt_be.entity.Lineage;
import in.shvms.famt_be.repo.AuditLogRepo;
import in.shvms.famt_be.repo.LineageRepo;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Transactional
public class LineageService {

    private final LineageRepo lineageRepo;
    private final AuditLogRepo auditLogRepo;

    // Helper method for audit logging
    private void logAudit(String tenantId, String userId, String action, String entityType, String entityId, Map<String, Object> details) {
        AuditLog auditLog = new AuditLog(
                null, // Id will be generated by MongoDB
                tenantId,
                LocalDateTime.now(),
                userId,
                action,
                entityType,
                entityId,
                details,
                null // IP address can be retrieved from request context if needed
        );
        auditLogRepo.save(auditLog);
    }

    public Lineage createLineage(String tenantId, String userId, Lineage lineage) {
        lineage.setTenantId(tenantId);
        Lineage savedLineage = lineageRepo.save(lineage);
        logAudit(tenantId, userId, "CREATE", "Lineage", savedLineage.getId().toString(), Map.of("newLineage", savedLineage));
        return savedLineage;
    }

    public Optional<Lineage> getLineageById(String tenantId, UUID id) {
        return lineageRepo.findByTenantIdAndId(tenantId, id);
    }

    public List<Lineage> getAllLineages(String tenantId) {
        return lineageRepo.findAllByTenantId(tenantId);
    }

    public Lineage updateLineage(String tenantId, String userId, UUID id, Lineage updatedLineage) {
        return lineageRepo.findByTenantIdAndId(tenantId, id).map(lineage -> {
            Map<String, Object> oldLineage = Map.of("oldName", lineage.getName());
            lineage.setName(updatedLineage.getName());
            // Update other fields as needed
            Lineage savedLineage = lineageRepo.save(lineage);
            logAudit(tenantId, userId, "UPDATE", "Lineage", savedLineage.getId().toString(), Map.of("oldValues", oldLineage, "newValues", Map.of("name", savedLineage.getName())));
            return savedLineage;
        }).orElseThrow(() -> new RuntimeException("Lineage not found"));
    }

    public void deleteLineage(String tenantId, String userId, UUID id) {
        Lineage lineageToDelete = lineageRepo.findByTenantIdAndId(tenantId, id)
                .orElseThrow(() -> new RuntimeException("Lineage not found"));
        lineageRepo.delete(lineageToDelete);
        logAudit(tenantId, userId, "DELETE", "Lineage", id.toString(), Map.of("deletedLineage", lineageToDelete));
    }
}