package in.shvms.famt_be.service;

import in.shvms.famt_be.dto.LocationDto;
import in.shvms.famt_be.entity.AuditLog;
import in.shvms.famt_be.entity.Location;
import in.shvms.famt_be.entity.LocationType;
import in.shvms.famt_be.repo.AuditLogRepo;
import in.shvms.famt_be.repo.LocationRepo;
import io.micrometer.common.lang.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class LocationService {

    private final LocationRepo locationRepo;
    private final AuditLogRepo auditLogRepo;

    // Helper method for audit logging
    private void logAudit(String tenantId, String userId, String action, String entityType, String entityId, Map<String, Object> details) {
        AuditLog auditLog = new AuditLog(
                null, // Id will be generated by MongoDB
                tenantId,
                LocalDateTime.now(),
                userId,
                action,
                entityType,
                entityId,
                details,
                null // IP address can be retrieved from request context if needed
        );
        auditLogRepo.save(auditLog);
    }

    public List<Location> findAll() {
        return locationRepo.findAll();
    }

    public Optional<Location> getLocationById(String id) {
        return locationRepo.findById(id);
    }

    public List<Location> getLocationsByType(LocationType locationType) {
        return locationRepo.findAllByLocationType(locationType);
    }

    public Location createLocation(String tenantId, String userId, LocationDto locationDto) {
        log.info("Creating location: {}", locationDto);
        if (locationDto.locationType() == LocationType.COUNTRY || locationDto.locationType() == LocationType.PLANET) {
            throw new IllegalArgumentException("Cannot create Planet or Country locations via this service. They should be pre-populated.");
        }
        if (locationDto.parentLocationId() == null) {
            throw new IllegalArgumentException("Parent location id is required while creating a new location.");
        }
        Location parentLocation = getParentLocation(locationDto.parentLocationId(), locationDto.locationType());
        Location location = new Location(locationDto.locationName(), locationDto.locationType());
        location.setParentLocation(parentLocation);
        location.setId(generateLocationId(location));
        locationRepo.save(location);
        addAsChildInParentLocation(location);
        logAudit(tenantId, userId, "CREATE", "Location", location.getId(), Map.of("newLocation", location));
        log.info("Location created successfully: {}", location);
        return location;
    }

    public Location createChildLocation(String tenantId, String userId, String parentId, LocationDto childLocationDto) {
        Optional<Location> parentOpt = locationRepo.findById(parentId);
        if (parentOpt.isEmpty()) {
            throw new RuntimeException("Parent location not found with ID: " + parentId);
        }
        Location parentLocation = parentOpt.get();

        // Validate child location type based on parent type
        if (!isValidChildType(parentLocation.getLocationType(), childLocationDto.locationType())) {
            throw new IllegalArgumentException(String.format("Invalid child location type %s for parent location type %s",
                    childLocationDto.locationType(), parentLocation.getLocationType()));
        }

        // Create the child location
        Location childLocation = new Location(childLocationDto.locationName(), childLocationDto.locationType());
        childLocation.setParentLocation(parentLocation);
        childLocation.setId(generateLocationId(childLocation));
        locationRepo.save(childLocation);
        addAsChildInParentLocation(childLocation);
        logAudit(tenantId, userId, "CREATE_CHILD", "Location", childLocation.getId(), Map.of("parentLocationId", parentId, "childLocation", childLocation));
        log.info("Child location {} created successfully under parent {}", childLocation, parentLocation);
        return childLocation;
    }
    
    public Optional<Location> updateLocation(String tenantId, String userId, String id, LocationDto locationDto) {
        log.info("Updating location with id: {} with \n LocationDto: {}", id, locationDto);
        return locationRepo.findById(id).map(location -> {
                log.info("Location found: {}", location);
                Map<String, Object> oldValues = Map.of(
                        "oldLocationName", location.getLocationName(),
                        "oldLocationType", location.getLocationType(),
                        "oldParentLocationId", Optional.ofNullable(location.getParentLocation()).map(Location::getId).orElse("N/A")
                );

                location.setLocationName(locationDto.locationName());
                // Location type should not typically be changed after creation
                // If it can be changed, more complex validation is needed for parent/child relationships
                // For now, assuming locationType is immutable or handled with extreme care
                // location.setLocationType(locationDto.locationType());

                if (locationDto.parentLocationId() != null && !Objects.equals(location.getParentLocation().getId(), locationDto.parentLocationId())) {
                    // Remove from old parent
                    removeAsChildInParentLocation(location);
                    // Set new parent
                    Location newParentLocation = getParentLocation(locationDto.parentLocationId(), location.getLocationType());
                    location.setParentLocation(newParentLocation);
                    // Add to new parent
                    addAsChildInParentLocation(location);
                }

                // If childLocationIds are provided in DTO, they override existing ones
                if (locationDto.childLocationIds() != null) {
                    location.setChildLocationIds(getChildLocations(locationDto.childLocationIds(), location.getLocationType()));
                    updateParentInChildLocations(location); // Update children's parent reference
                }
                
                // Recalculate ID if locationName or parent changed
                String newId = generateLocationId(location);
                if (!newId.equals(location.getId())) {
                    // If ID changes, it's essentially a delete + create,
                    // or we need to handle ID change in Neo4j if supported
                    // For now, simpler approach: delete old, save new, update children that referenced old ID
                    deleteNodeByIdInternal(id); // Delete old node
                    location.setId(newId); // Set new ID
                    Location savedLocation = locationRepo.save(location); // Save new node
                    // Re-add as child in new parent if ID changed and it was moved
                    // This is handled by addAsChildInParentLocation if parent is new
                    // Or if old parent is same, but ID changed, parent's child list needs update
                    if (locationDto.parentLocationId() == null) { // If parent didn't change
                        addAsChildInParentLocation(savedLocation); // Ensure old parent references new ID
                    }
                    // Children need to be updated to point to the new ID of this location
                    // This is partly handled by updateParentInChildLocations, but needs to be robust for ID change
                } else {
                    Location savedLocation = locationRepo.save(location);
                }

                logAudit(tenantId, userId, "UPDATE", "Location", id, Map.of("oldValues", oldValues, "newValues", location));
                log.info("Location updated successfully: {}", location);
                return location;
        }).orElseThrow(() -> new RuntimeException("Location not found with id: " + id));
    }

    public void deleteLocation(String tenantId, String userId, String id) {
        log.info("Deleting location with id: {}", id);
        Location location = locationRepo.findById(id)
                .orElseThrow(() -> new RuntimeException("Location id: " + id + " not found"));

        if (location.getLocationType() == LocationType.COUNTRY || location.getLocationType() == LocationType.PLANET) {
            throw new IllegalArgumentException("Cannot delete Planet or Country locations.");
        }
        
        // Prevent deletion if it has children
        if (location.getChildLocationIds() != null && !location.getChildLocationIds().isEmpty()) {
            throw new IllegalStateException("Cannot delete location " + id + " as it has child locations. Please delete children first.");
        }

        removeAsChildInParentLocation(location);
        locationRepo.deleteById(id);
        logAudit(tenantId, userId, "DELETE", "Location", id, Map.of("deletedLocation", location));
        log.info("Location id: {} deleted successfully", id);
    }

    public Optional<Location> findLocationByNameAndParent(String locationName, String parentLocationId) {
        return locationRepo.findByLocationNameAndParentLocationId(locationName, parentLocationId);
    }

    private void deleteNodeByIdInternal(String id) {
        log.info("Internal deletion of location with id: {}", id);
        locationRepo.deleteById(id);
    }

    private void updateParentInChildLocations(Location location) {
        if (location.getChildLocationIds() != null) {
            locationRepo.findAllById(location.getChildLocationIds()).forEach(childLocation -> {
                childLocation.setParentLocation(location);
                locationRepo.save(childLocation);
                log.debug("Updated parent location id: {} in location id: {}", location.getId(), childLocation.getId());
            });
        }
    }        
    
    private void removeAsChildInParentLocation(Location location) {
        locationRepo.findById(location.getParentLocation().getId()).ifPresent(parentLocation ->{
            if (Objects.nonNull(parentLocation.getChildLocationIds())) {
                parentLocation.getChildLocationIds().removeIf(childLocationId -> childLocationId.equals(location.getId()));
                locationRepo.save(parentLocation);
                log.debug("Removed Child Location id: {} from Parent Location id: {}", location.getId(), parentLocation.getId());
            }
        });
    }

    private void addAsChildInParentLocation(Location location) {
        locationRepo.findById(location.getParentLocation().getId()).ifPresent(parentLocation ->{
            if (Objects.isNull(parentLocation.getChildLocationIds())) {
                parentLocation.setChildLocationIds(new HashSet<>());
            }
            parentLocation.getChildLocationIds().add(location.getId());
            locationRepo.save(parentLocation);
            log.debug("Added Child Location id: {} to Parent Location id: {}", location.getId(), parentLocation.getId());
        });
    }
    
    private static String generateLocationId(Location location) {
        // Village Bhopati -> VIL_PAR_BHO
        return 
        location.getLocationType().name().substring(0, 3).toLowerCase() + 
        "_" +
        Stream.of(location.getParentLocation().getLocationName().toLowerCase().trim().split(" ")).map(s -> s.substring(0, Math.min(s.length(), 5))).collect(Collectors.joining()) +
        "_" +
        Stream.of(location.getLocationName().toLowerCase().trim().split(" ")).map(s -> s.substring(0, Math.min(s.length(), 5))).collect(Collectors.joining());
    }

    private Location getParentLocation(@NonNull String parentId, LocationType childLocationType) {
        Optional<Location> parentLocation = locationRepo.findById(parentId);
        if (parentLocation.isEmpty()) {
            throw new RuntimeException(String.format("Parent location %s not found", parentId));
        }
        Location foundParent = parentLocation.get();

        if (!isValidParentType(foundParent.getLocationType(), childLocationType)) {
            throw new IllegalArgumentException(String.format("Invalid parent location type %s for child location type %s",
                    foundParent.getLocationType(), childLocationType));
        }
        return foundParent;
    }

    private boolean isValidParentType(LocationType parentType, LocationType childType) {
        return switch (childType) {
            case STATE -> parentType == LocationType.COUNTRY;
            case DISTRICT -> parentType == LocationType.STATE;
            case TOWN -> parentType == LocationType.DISTRICT;
            case VILLAGE -> parentType == LocationType.TOWN;
            default -> false; // PLANET and COUNTRY are top-level or handled separately
        };
    }

    private boolean isValidChildType(LocationType parentType, LocationType childType) {
        return switch (parentType) {
            case COUNTRY -> childType == LocationType.STATE;
            case STATE -> childType == LocationType.DISTRICT;
            case DISTRICT -> childType == LocationType.TOWN;
            case TOWN -> childType == LocationType.VILLAGE;
            default -> false;
        };
    }

    private Set<String> getChildLocations(List<String> childLocationIds, LocationType parentLocationType) {
        return childLocationIds.stream().map(childLocationId -> {
            return getChildLocation(childLocationId, parentLocationType); 
        }).map(Location::getId).collect(Collectors.toSet());
    }
    private Location getChildLocation(@NonNull String childLocationId, LocationType parentLocationType) {
        Optional<Location> childLocation = locationRepo.findById(childLocationId);
        if (childLocation.isEmpty()) {
            throw new RuntimeException(String.format("Child location %s not found", childLocationId));
        }
        Location foundChild = childLocation.get();

        if (!isValidChildType(parentLocationType, foundChild.getLocationType())) {
            throw new IllegalArgumentException(String.format("Invalid child location type %s for parent location type %s",
                    foundChild.getLocationType(), parentLocationType));
        }
        return foundChild;
    }
    
    public Location getEarthLocation() {
        return locationRepo.findByLocationNameAndLocationType("Earth", LocationType.PLANET)
                .orElseThrow(() -> new RuntimeException("Earth location not found in database"));
    }
}