package in.shvms.famt_be.service;

import in.shvms.famt_be.entity.AuditLog;
import in.shvms.famt_be.entity.ParentChildRelation;
import in.shvms.famt_be.entity.ParentChildType;
import in.shvms.famt_be.entity.Person;
import in.shvms.famt_be.entity.SpousalRelation;
import in.shvms.famt_be.entity.SpousalStatus;
import in.shvms.famt_be.repositories.mongo.AuditLogRepository;
import in.shvms.famt_be.repositories.neo4j.PersonRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class PersonService {

    private final PersonRepository personRepo;
    private final AuditLogRepository auditLogRepo;

    // Helper method for audit logging
    private void logAudit(String tenantId, String userId, String action, String entityType, String entityId, Map<String, Object> details) {
        AuditLog auditLog = new AuditLog(
                null, // Id will be generated by MongoDB
                tenantId,
                LocalDateTime.now(),
                userId,
                action,
                entityType,
                entityId,
                details,
                null // IP address can be retrieved from request context if needed
        );
        auditLogRepo.save(auditLog);
    }

    public Person createPerson(String tenantId, String userId, Person person) {
        person.setTenantId(tenantId);
        if (person.getSpouseRelations() == null) {
            person.setSpouseRelations(new HashSet<>());
        }
        if (person.getChildrenRelations() == null) {
            person.setChildrenRelations(new HashSet<>());
        }
        if (person.getFriends() == null) {
            person.setFriends(new HashSet<>());
        }
        if (person.getLifeEvents() == null) {
            person.setLifeEvents(new HashSet<>());
        }
        Person savedPerson = personRepo.save(person);
        logAudit(tenantId, userId, "CREATE", "Person", savedPerson.getId().toString(), Map.of("newPerson", savedPerson));
        return savedPerson;
    }

    public Optional<Person> getPersonById(String tenantId, UUID id) {
        return personRepo.findByTenantIdAndId(tenantId, id);
    }

    public List<Person> getAllPeople(String tenantId) {
        return personRepo.findAllByTenantId(tenantId);
    }

    public Person updatePerson(String tenantId, String userId, UUID id, Person updatedPerson) {
        return personRepo.findByTenantIdAndId(tenantId, id).map(person -> {
            Map<String, Object> oldValues = Map.of(
                    "firstName", Optional.ofNullable(person.getFirstName()).orElse(""),
                    "lastName", Optional.ofNullable(person.getLastName()).orElse(""),
                    "maidenName", Optional.ofNullable(person.getMaidenName()).orElse(""),
                    "petName", Optional.ofNullable(person.getPetName()).orElse(""),
                    "gender", Optional.ofNullable(person.getGender()).map(Enum::name).orElse(""),
                    "dateOfBirth", Optional.ofNullable(person.getDateOfBirth()).map(LocalDate::toString).orElse(""),
                    "dateOfDeath", Optional.ofNullable(person.getDateOfDeath()).map(LocalDate::toString).orElse("")
            );

            person.setFirstName(updatedPerson.getFirstName());
            person.setLastName(updatedPerson.getLastName());
            person.setMaidenName(updatedPerson.getMaidenName());
            person.setPetName(updatedPerson.getPetName());
            person.setGender(updatedPerson.getGender());
            person.setDateOfBirth(updatedPerson.getDateOfBirth());
            person.setDateOfDeath(updatedPerson.getDateOfDeath());
            // Other fields can be updated similarly

            Person savedPerson = personRepo.save(person);

            Map<String, Object> newValues = Map.of(
                    "firstName", Optional.ofNullable(savedPerson.getFirstName()).orElse(""),
                    "lastName", Optional.ofNullable(savedPerson.getLastName()).orElse(""),
                    "maidenName", Optional.ofNullable(savedPerson.getMaidenName()).orElse(""),
                    "petName", Optional.ofNullable(savedPerson.getPetName()).orElse(""),
                    "gender", Optional.ofNullable(savedPerson.getGender()).map(Enum::name).orElse(""),
                    "dateOfBirth", Optional.ofNullable(savedPerson.getDateOfBirth()).map(LocalDate::toString).orElse(""),
                    "dateOfDeath", Optional.ofNullable(savedPerson.getDateOfDeath()).map(LocalDate::toString).orElse("")
            );
            logAudit(tenantId, userId, "UPDATE", "Person", savedPerson.getId().toString(), Map.of("oldValues", oldValues, "newValues", newValues));
            return savedPerson;
        }).orElseThrow(() -> new RuntimeException("Person not found"));
    }

    public void deletePerson(String tenantId, String userId, UUID id) {
        Person personToDelete = personRepo.findByTenantIdAndId(tenantId, id)
                .orElseThrow(() -> new RuntimeException("Person not found or not accessible by tenant."));
        personRepo.delete(personToDelete);
        logAudit(tenantId, userId, "DELETE", "Person", id.toString(), Map.of("deletedPerson", personToDelete));
    }

    public Person addParentChildRelation(String tenantId, String userId, UUID parentId, UUID childId, ParentChildType type, LocalDate startDate, Double confidenceScore) {
        Person parent = personRepo.findByTenantIdAndId(tenantId, parentId)
                .orElseThrow(() -> new RuntimeException("Parent not found or not accessible by tenant."));
        Person child = personRepo.findByTenantIdAndId(tenantId, childId)
                .orElseThrow(() -> new RuntimeException("Child not found or not accessible by tenant."));

        if (child.getChildrenRelations() == null) {
            child.setChildrenRelations(new HashSet<>());
        }
        ParentChildRelation relation = new ParentChildRelation(null, parent, type, confidenceScore, startDate);
        child.getChildrenRelations().add(relation);
        Person savedChild = personRepo.save(child);
        logAudit(tenantId, userId, "ADD_RELATION", "ParentChildRelation", childId.toString(), Map.of(
                "parentId", parentId.toString(),
                "childId", childId.toString(),
                "type", type.name(),
                "startDate", Optional.ofNullable(startDate).map(LocalDate::toString).orElse("N/A"),
                "confidenceScore", Optional.ofNullable(confidenceScore).map(Object::toString).orElse("N/A")
        ));
        return savedChild;
    }

    public Person addSpousalRelation(String tenantId, String userId, UUID person1Id, UUID person2Id, SpousalStatus status, LocalDate startDate, LocalDate endDate, String partnershipType) {
        Person person1 = personRepo.findByTenantIdAndId(tenantId, person1Id)
                .orElseThrow(() -> new RuntimeException("Person 1 not found or not accessible by tenant."));
        Person person2 = personRepo.findByTenantIdAndId(tenantId, person2Id)
                .orElseThrow(() -> new RuntimeException("Person 2 not found or not accessible by tenant."));

        if (person1.getSpouseRelations() == null) {
            person1.setSpouseRelations(new HashSet<>());
        }
        if (person2.getSpouseRelations() == null) {
            person2.setSpouseRelations(new HashSet<>());
        }

        SpousalRelation relation1 = new SpousalRelation(null, person2, startDate, endDate, status, partnershipType);
        person1.getSpouseRelations().add(relation1);
        SpousalRelation relation2 = new SpousalRelation(null, person1, startDate, endDate, status, partnershipType);
        person2.getSpouseRelations().add(relation2);

        personRepo.save(person1);
        Person savedPerson2 = personRepo.save(person2);
        logAudit(tenantId, userId, "ADD_RELATION", "SpousalRelation", person1Id.toString(), Map.of(
                "person1Id", person1Id.toString(),
                "person2Id", person2Id.toString(),
                "status", status.name(),
                "startDate", Optional.ofNullable(startDate).map(LocalDate::toString).orElse("N/A"),
                "endDate", Optional.ofNullable(endDate).map(LocalDate::toString).orElse("N/A"),
                "partnershipType", Optional.ofNullable(partnershipType).orElse("N/A")
        ));
        return savedPerson2;
    }

    public Person addFriendRelation(String tenantId, String userId, UUID person1Id, UUID person2Id) {
        Person person1 = personRepo.findByTenantIdAndId(tenantId, person1Id)
                .orElseThrow(() -> new RuntimeException("Person 1 not found or not accessible by tenant."));
        Person person2 = personRepo.findByTenantIdAndId(tenantId, person2Id)
                .orElseThrow(() -> new RuntimeException("Person 2 not found or not accessible by tenant."));

        if (person1.getFriends() == null) {
            person1.setFriends(new HashSet<>());
        }
        if (person2.getFriends() == null) {
            person2.setFriends(new HashSet<>());
        }

        person1.getFriends().add(person2);
        person2.getFriends().add(person1);

        personRepo.save(person1);
        Person savedPerson2 = personRepo.save(person2);
        logAudit(tenantId, userId, "ADD_RELATION", "FriendRelation", person1Id.toString(), Map.of(
                "person1Id", person1Id.toString(),
                "person2Id", person2Id.toString()
        ));
        return savedPerson2;
    }

    public List<Person> findPeopleByName(String tenantId, String name) {
        return personRepo.findByTenantIdAndFirstNameContaining(tenantId, name);
    }

    public List<Person> findPeopleByLineage(String tenantId, UUID lineageId) {
        return personRepo.findAllByTenantIdAndLineageId(tenantId, lineageId);
    }
}