package in.shvms.famt_be.service;

import in.shvms.famt_be.entity.AuditLog;
import in.shvms.famt_be.entity.User;
import in.shvms.famt_be.entity.UserRole;
import in.shvms.famt_be.repositories.mongo.AuditLogRepository;
import in.shvms.famt_be.repositories.mongo.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

@Service
@RequiredArgsConstructor
@Transactional
public class UserService {

    private final UserRepository userRepo;
    private final AuditLogRepository auditLogRepo;
    private final PasswordEncoder passwordEncoder;

    // Helper method for audit logging
    private void logAudit(String tenantId, String userId, String action, String entityType, String entityId, Map<String, Object> details) {
        AuditLog auditLog = new AuditLog(
                null, // Id will be generated by MongoDB
                tenantId,
                LocalDateTime.now(),
                userId,
                action,
                entityType,
                entityId,
                details,
                null // IP address can be retrieved from request context if needed
        );
        auditLogRepo.save(auditLog);
    }

    public User createUser(String tenantId, String actingUserId, String username, String password, Set<UserRole> roles) {
        if (userRepo.findByUsername(username).isPresent()) {
            throw new IllegalArgumentException("Username already exists");
        }
        User newUser = new User(
                null,
                tenantId,
                username,
                passwordEncoder.encode(password),
                roles,
                true
        );
        User savedUser = userRepo.save(newUser);
        logAudit(tenantId, actingUserId, "CREATE", "User", savedUser.getId(), Map.of("newUser", savedUser.getUsername(), "roles", savedUser.getRoles()));
        return savedUser;
    }

    public Optional<User> getUserById(String tenantId, String id) {
        return userRepo.findByTenantIdAndId(tenantId, id);
    }

    public Optional<User> getUserByUsername(String username) {
        return userRepo.findByUsername(username);
    }

    public List<User> getAllUsers(String tenantId) {
        return userRepo.findAllByTenantId(tenantId);
    }

    public User updateUser(String tenantId, String actingUserId, String id, Set<UserRole> newRoles, Boolean isActive) {
        return userRepo.findByTenantIdAndId(tenantId, id).map(user -> {
            Map<String, Object> oldUser = Map.of("oldRoles", user.getRoles(), "oldIsActive", user.isActive());
            user.setRoles(newRoles);
            user.setActive(isActive != null ? isActive : user.isActive());
            User savedUser = userRepo.save(user);
            logAudit(tenantId, actingUserId, "UPDATE", "User", savedUser.getId(), Map.of("oldValues", oldUser, "newValues", Map.of("roles", savedUser.getRoles(), "isActive", savedUser.isActive())));
            return savedUser;
        }).orElseThrow(() -> new RuntimeException("User not found"));
    }

    public void deleteUser(String tenantId, String actingUserId, String id) {
        User userToDelete = userRepo.findByTenantIdAndId(tenantId, id)
                .orElseThrow(() -> new RuntimeException("User not found"));
        userRepo.delete(userToDelete);
        logAudit(tenantId, actingUserId, "DELETE", "User", id, Map.of("deletedUser", userToDelete.getUsername()));
    }

    public boolean authenticateUser(String username, String password) {
        Optional<User> userOptional = userRepo.findByUsername(username);
        if (userOptional.isPresent()) {
            User user = userOptional.get();
            // In a real application, JWT generation would happen here after successful authentication
            return passwordEncoder.matches(password, user.getPassword());
        }
        return false;
    }

    // Method to generate JWT token would be in a separate utility or security config
}